manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      # ZMK main as of 2026-08-16. Pin it so successful builds stay reproducible.
      revision: 6e2ef41e022d555b10f116e395832913f71717b3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      # PMW3610 ALT driver main as of 2026-08-20.
      revision: 44b4a76b74d293a93cec4ccb7e04cb8d29c10f93
  self:
    path: config
